version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql-storage:/var/opt/mssql

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mssql


volumes:
  mssql-storage:

# --Adminer:
# --database system: MS SQL
# --server: sqlserver
# --user: sa
# --password: YourStrong!Passw0rd
# --database: empty or master
