-
  hosts: linux

  vars:
    jobids: []

  tasks:
    - name: Task 1
      command: /bin/sleep 5
      async: 10
      poll: 0
      register: result1

    - name: Task 2
      command: /bin/sleep 5
      async: 10
      poll: 0
      register: result2

    - name: Task 3
      command: /bin/sleep 5
      async: 10
      poll: 0
      register: result3

    - name: Task 4
      command: /bin/sleep 30
      async: 60
      poll: 0
      register: result4

    - name: Task 5
      command: /bin/sleep 5
      async: 10
      poll: 0
      register: result5

    - name: Task 6
      command: /bin/sleep 5
      async: 10
      poll: 0
      register: result6

    - name: Capture Job IDs
      set_fact:
        jobids: >
                {% if item.ansible_job_id is defined -%}
                  {{ jobids + [item.ansible_job_id] }}
                {% else -%}
                  {{ jobids }}
                {% endif %}
      with_items: "{{ [ result1, result2, result3, result4, result5, result6 ] }}"

    - name: Show Job IDs
      debug:
        var: jobids

    - name: 'Wait for Job IDs'
      async_status:
         jid: "{{ item }}"
      with_items: "{{ jobids }}"
      register: jobs_result
      until: jobs_result.finished
      retries: 30